name: ovoride_driver
description: OvoRide is a complete ride-sharing solution.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+14

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dotted_border: ^3.1.0
  file_picker: ^10.3.3
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_foreground_task: ^9.1.0
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^19.5.0
  flutter_polyline_points: ^3.1.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.2
  http: ^1.2.0
  mapbox_maps_flutter: ^2.18.0
  flutter_widget_from_html: ^0.17.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_fonts: ^6.2.1
  get: ^4.7.2
  latlong2: ^0.9.1 # ✅ أضف هذا السطر
  flutter_secure_storage: any
  firebase_auth: any
  agora_rtc_engine: ^6.3.0  # محرك الاتصال
  audioplayers: any
  google_sign_in: ^7.2.0
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.2.0
  in_app_review: ^2.0.11
  intl: ^0.20.2
  just_audio: ^0.10.5
  logger: ^2.6.2
  lottie: ^3.3.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pinput: ^5.0.2
  pusher_channels_flutter: ^2.5.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  timelines_plus: ^1.0.8
  timezone: 0.10.1
  toastification: ^3.0.3
  url_launcher: ^6.3.2
  vibration: ^3.1.4
  zoom_tap_animation: ^1.1.0
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: any
  file_picker: any
  just_audio: any
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/onboard/
    - assets/images/social/
    - assets/icon/
    - assets/animation/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
